# Sample configuration file for image-alignment system

[algorithms.orb]
max_features = 500
scale_factor = 1.5
n_levels = 8
edge_threshold = 31
first_level = 0
wta_k = 2
score_type = 0
patch_size = 31
fast_threshold = 20
distance_threshold = 100.0
ratio_threshold = 0.7

[algorithms.template]
distance_threshold = 0.8
match_threshold = 0.7
normalization_factor = 1.0
confidence_threshold = 0.5

[algorithms.akaze]
threshold = 0.001
octaves = 4
octave_layers = 4
diffusivity = 1
max_features = 1000
distance_threshold = 100.0
ratio_threshold = 0.7


[algorithms.sift]
n_features = 1000
n_octave_layers = 3
contrast_threshold = 0.02
edge_threshold = 5.0
sigma = 1.6
distance_threshold = 100.0

[algorithms.ransac]
max_iterations = 1000
inlier_threshold = 1.5
min_inliers = 2
success_probability = 0.99
outlier_ratio = 0.5
early_exit_threshold = 0.95

[image]
min_size = 8
max_size = 10000
default_patch_sizes = [32, 64, 128]
variance_threshold = 100.0
min_features_for_alignment = 10
pyramid_levels = 3
edge_detection_threshold = 50.0
gaussian_blur_sigma = 1.0

[augmentation.noise]
gaussian_std_range = [0.0, 10.0]
salt_pepper_ratio = 0.05
uniform_range = [-10.0, 10.0]
enable_gaussian = true
enable_salt_pepper = true
enable_uniform = true

[augmentation.blur]
gaussian_kernel_range = [3, 15]
gaussian_sigma_range = [0.5, 3.0]
motion_length_range = [5, 20]
motion_angle_range = [0.0, 360.0]
enable_gaussian = true
enable_motion = true

[augmentation.lighting]
brightness_range = [-30.0, 30.0]
contrast_range = [0.7, 1.3]
gamma_range = [0.7, 1.3]
exposure_range = [-1.0, 1.0]
enable_brightness = true
enable_contrast = true
enable_gamma = true
enable_exposure = true

[augmentation.geometric]
rotation_range = [-30.0, 30.0]
scale_range = [0.8, 1.2]
translation_range = [-50.0, 50.0]
shear_range = [-0.2, 0.2]
enable_rotation = true
enable_scale = true
enable_translation = true
enable_shear = true

[augmentation.distortion]
barrel_distortion_range = [-0.3, -0.1]
pincushion_distortion_range = [0.1, 0.3]
perspective_distortion_strength = 0.1
enable_barrel = true
enable_pincushion = true
enable_perspective = true

[testing]
accuracy_threshold_pixels = 0.1
rotation_accuracy_threshold_degrees = 0.5
scale_accuracy_threshold = 0.01
min_confidence_threshold = 0.5
max_processing_time_ms = 50.0
test_repetitions = 3
validation_sample_size = 100
benchmark_iterations = 10

[dashboard]
default_port = 3000
request_timeout_ms = 5000
max_concurrent_requests = 100
static_file_cache_duration_secs = 3600
enable_cors = true
max_upload_size_mb = 10
results_per_page = 20
chart_colors = ["#3498db", "#e74c3c", "#2ecc71", "#f39c12", "#9b59b6", "#1abc9c"]

[validation.success_criteria]
translation_accuracy_px = 12.8  # 20% of 64px patch
min_confidence = 0.3

[validation.confidence_thresholds]
orb = 0.5
template = 0.7
akaze = 0.6
sift = 0.6

[validation.performance_targets]
target_processing_time_ms = 25.0
target_accuracy_px = 0.05
target_success_rate = 0.95

[logging]
global_level = "info"
console_output = true
log_directory = "logs"
include_file_location = false
algorithm_level = "debug"
pipeline_level = "info"
testing_level = "debug"
dashboard_level = "info"

[logging.rotation]
max_file_size = 104857600  # 100MB
max_file_age_hours = 24
max_files = 10
archive_directory = "logs/archive"
compress_archives = true